### ISSUE TITLE
How can I restore it to plaintext

### ISSUE THREAD

**Issue by lideen999** [iquerejeta/elgamal#3]
let pltxt = RistrettoPoint::hash_from_bytes::<Sha512>("aa".as_bytes());
 let enc_pltxt = pk.encrypt(pltxt);
let txt = sk.decrypt(enc_pltxt);

**txt is RistrettoPoint ,  can I restore it to plaintext "aa "**

**Comment by iquerejeta** [comment]
The type of `txt` is the same as `pltxt`, which is a RistrettoPoint. The ElGamal encryption works by encrypting messages which are in the group defined by the ElGamal parameters (which in our case these are points from the curve Curve25519 in the Ristretto prime order group, i.e.: RistrettoPoints). 
The way one encodes a string to an elliptic curve point (and back) is still out of the scope of the current version.  
We might include these functionalities in the near future, however note that these are not standard. 
The main functionalities of Elliptic Curve Cryptography are Key Exchange and Digital signature. In our next iteration we will provide documentation of how the cryptosystem works and why it is not suitable for generic encryption-decryption.

**Comment by lideen999** [comment]
This function is very important. We look forward to releasing it as soon as possible
