### ISSUE TITLE
Adding and substrating Ciphertext with RistrettoPoint

### ISSUE THREAD

**Issue by contrun** [iquerejeta/elgamal#5]
In our application, it is desirable to have an addition between Ciphertext $(m_1 + r*y, r*g)$ and RistrettoPoint $(m_2) \equiv (m_2 + 0*0, 0*g)$ defined as follows

$(m_1 + r*y, r*g) + (m_2 + 0*0, 0*g) = (m_1 + m_2 + r*y, r*g)$

I am willing to submit a PR which define Plaintext as a wrapper around RistrettoPoint, and implements addition between Ciphertext and Plaintext.

This, of cause, complicates things. What's your thought on this? Will you accept a pr like that?

**Comment by gpestana** [comment]
PRs are always welcome! Could you elaborate on the changes needed?

@iquerejeta what do you think about this feature?

**Comment by contrun** [comment]
@gpestana 

Let $g$ be a base point, $x$ and $y$ be two public keys, $m_1$ and $m_2$ be two ristretto points.
We can view a RistrettoPoint $(m_1)$ equivalent to Ciphertext $(m_1 + 0x, 0g)$, and define the subtraction of RistrettoPoint and Ciphertext as
$(0g, m_1 + 0x) - (rg, m_2 + ry) = (rg, m_1 - m_2 + ry)$.
We can decipher the ciphertext with the secret key of the original ciphertext. This is can be useful in some case, for example, we can calculate the subtraction of plaintext transaction fee and ciphertext balance. The resulting ciphertext can be deciphered with the original secret key.


I just created a pr https://github.com/iquerejeta/elgamal/pull/7

**Comment by iquerejeta** [comment]
Yes. Reasonable feature. I see some applications were it would be of use. I'll accept the PR request. Thanks! And don't hesitate to directly open a PR when you come up with a limitation like this one.
